http:
  host: "localhost"
  port: 4000

db:
  primary:
    type: "postgres"
    host: "172.105.42.206"
    port: 4002
    database: "sh_client"
    password: "sharents-client-admin"
    username: "sharents-client-admin"
    synchronize: false
    logging: true

client:
  password:
    randomByte: 16
    iteration: 1000
    keyLen: 64
    digest: sha512
    secret: b2dad6475df337c5054266f328631849eee7099d20d527e22b72058cae89602e
