http:
  host: "localhost"
  port: 4000

db:
  primary:
    type: "postgres"
    host: "172.105.42.206"
    port: 4002
    database: "sh_client"
    password: "sharents-client-admin"
    username: "sharents-client-admin"
    synchronize: false
    logging: true

client:
  session:
    secret: f415bd3f8d8f3e12e5be58373011220c588da6076cbefc73d3e1fa3bfbb3bacf
  password:
    randomByte: 16
    iteration: 1000
    keyLen: 64
    digest: sha512
    secret: b2dad6475df337c5054266f328631849eee7099d20d527e22b72058cae89602e

  token:
    accessToken:
      secretKey: e51769af88087e41dfd2e70cd4f1ca1ead04c89f859e2f32c7f70123daec715e84121a87362b165cee21fb40ce5dfd84952b122af7d8094bd8e975f021f6a3fe
      expireTime: "1h"

    refreshToken:
      secretKey: e8c7e1196951096463360e3b53e0e191fb6eec2a6e01e2999fdbdf99a84c982ac3ddc9c5c4627114ebebb1b20ed34eab1fc07f1b0ba6e99be115dfde43a4f741
      expireTime: "1d"

queue:
  rabbitmq:
    rabbitmqUser: sharents
    rabbitmqPass: sharents
    rabbitmqVhost: client
    rabbitmqPort: 5672
    rabbitmqHost: 192.168.0.2
    # rabbitmqExchange: client-exchange
    # rabbitmqRoute:
    #   mail: mail-route
    #   phone: phone-route


